apiVersion: v1
kind: Pod
metadata:
  name: dev-scope
  namespace: fais-1
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  # nodeSelector:
  #   kubernetes.io/hostname: gu08.sciclone.wm.edu
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - gu07.sciclone.wm.edu
                - gu08.sciclone.wm.edu
                - gu09.sciclone.wm.edu
                - gu10.sciclone.wm.edu
                # - gu11.sciclone.wm.edu
                - gu12.sciclone.wm.edu
                # - gu13.sciclone.wm.edu
                - gu14.sciclone.wm.edu
                - gu15.sciclone.wm.edu
                - gu16.sciclone.wm.edu
                - gu17.sciclone.wm.edu
                - gu18.sciclone.wm.edu
                - gu19.sciclone.wm.edu
  containers:
    - name: dev-scope
      #image: ghcr.io/stmorse/scope2:latest
      image: busybox:latest
      resources:
        requests:
          memory: '64Gi'
          #nvidia.com/gpu: '1'
          cpu: '4'
        limits:
          memory: '64Gi'
          #nvidia.com/gpu: '1'
          cpu: '4'
      command: ['/bin/sh']
      args:
        - '-c'
        - |
          echo "Running dev scope2 container..."   # pod is for dev'ing scripts, run indef
          sleep infinity
      env:
        - name: HF_HOME
          value: '/sciclone/home/stmorse/.cache/huggingface'
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
      volumeMounts:
        # - name: home
        #   mountPath: /sciclone/home/stmorse
        # - name: data
        #   mountPath: /sciclone/data10/twford/reddit/reddit
        - name: scope2
          mountPath: /app
        - name: proj-ds
          mountPath: /sciclone/proj-ds/geograd/stmorse
  volumes:
    # - name: home
    - name: scope2
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/stmorse/projects/scope2
    # - name: data
    #   nfs:
    #     server: 128.239.56.30
    #     path: /sciclone/data10/twford/reddit/reddit
    - name: proj-ds
      nfs:
        server: 192.168.59.144
        #server: 128.239.59.144
        #server: proj-ds-ib.sciclone.wm.edu
        path: /sciclone/proj-ds/geograd/stmorse
