apiVersion: v1
kind: Pod
metadata:
  name: run-scope2
  namespace: fais-1
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  # nodeSelector:
  #   kubernetes.io/hostname: gu15.sciclone.wm.edu
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - gu07.sciclone.wm.edu
                - gu08.sciclone.wm.edu
                - gu09.sciclone.wm.edu
                - gu10.sciclone.wm.edu
                # - gu11.sciclone.wm.edu
                - gu12.sciclone.wm.edu
                # - gu13.sciclone.wm.edu
                - gu14.sciclone.wm.edu
                - gu15.sciclone.wm.edu
                - gu16.sciclone.wm.edu
                - gu17.sciclone.wm.edu
                - gu18.sciclone.wm.edu
                - gu19.sciclone.wm.edu
  containers:
    - name: run-scope2
      image: ghcr.io/stmorse/scope2:latest
      resources:
        requests:
          memory: '64Gi'
          nvidia.com/gpu: '1'
          cpu: '4'
        limits:
          memory: '64Gi'
          nvidia.com/gpu: '1'
          cpu: '4'
      command: ['/bin/bash']
      args:
        - '-c'
        - |
          echo "Running scope2 container..."
          python main.py --path fender
          sleep infinity
      env:
        - name: HF_HOME
          value: '/sciclone/home/stmorse/.cache/huggingface'
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
      volumeMounts:
        - name: home
          mountPath: /sciclone/home/stmorse
        - name: scope2
          mountPath: /app
  volumes:
    - name: home
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/stmorse
    - name: scope2
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/stmorse/chs/scope2