# ── wrapper script ───────────────
apiVersion: v1
kind: ConfigMap
metadata:
  name: scope-sweep
  namespace: fais-1
data:
  run.sh: |
    #!/usr/bin/env bash
    set -euo pipefail

    IDX="${JOB_IDX:?}"

    # parameter grid
    A=("harm" "safe")

    # map index to combo
    A_IDX=$(( IDX % ${#A[@]} ))

    a_val="${A[A_IDX]}"

    ARGS=(
      --provider       "ollama"
      --candidates     3
      --simulations    30
      --depth          4
      --reward         "$a_val"
      --dname          "$a_val"
    )

    echo "> running combo #$IDX -> ${ARGS[*]}"
    exec python /app/main.py "${ARGS[@]}"
---
# ---- job ----
apiVersion: batch/v1
kind: Job
metadata:
  name: scope-grid
  namespace: fais-1
spec:
  # ttlSecondsAfterFinished: 300   # job (and pods) deleted 5 min after finish
  completions: 2        # total combos
  parallelism: 2         # num to run at once
  completionMode: Indexed
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 270999 # run id command in terminal to get your UID
        runAsGroup: 50038
        fsGroup: 1134
      # nodeSelector:
      #   kubernetes.io/hostname: gu15.sciclone.wm.edu
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - gu07.sciclone.wm.edu
                - gu08.sciclone.wm.edu
                - gu09.sciclone.wm.edu
                - gu10.sciclone.wm.edu
                # - gu11.sciclone.wm.edu
                - gu12.sciclone.wm.edu
                # - gu13.sciclone.wm.edu
                - gu14.sciclone.wm.edu
                - gu15.sciclone.wm.edu
                - gu16.sciclone.wm.edu
                - gu17.sciclone.wm.edu
                - gu18.sciclone.wm.edu
                - gu19.sciclone.wm.edu
      containers:
      - name: scope-grid
        image: ghcr.io/stmorse/scope2:latest
        resources:
          requests:
            memory: '64Gi'
            nvidia.com/gpu: '1'
            cpu: '4'
          limits:
            memory: '64Gi'
            nvidia.com/gpu: '1'
            cpu: '4'
        # mount the script from the ConfigMap
        volumeMounts:
        - name: script
          mountPath: /mnt/script
        - name: scope
          mountPath: "/app"
        - name: home
          mountPath: "/sciclone/home/stmorse"
        env:
        - name: HF_HOME
          value: '/sciclone/home/stmorse/.cache/huggingface'
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
        - name: JOB_IDX
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
        command: ["/bin/bash", "/mnt/script/run.sh"]
      volumes:
      - name: script
        configMap:
          name: scope-sweep
      - name: home
        nfs:
          server: 128.239.56.166
          path: /sciclone/home/stmorse
      - name: scope
        nfs:
          server: 128.239.59.144
          path: /sciclone/geograd/stmorse/chs/scope2
      imagePullSecrets:
      - name: ghcr-secret
      
